/* tslint:disable */
/* eslint-disable */
/**
 * GoMoney Football-League Manager Service
 * This service provides endpoints for all `football-league manager` related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fatai@mail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Fixture Unique-Link response-object
 * @export
 * @interface FixtureUniqueLinkResponse
 */
export interface FixtureUniqueLinkResponse {
    /**
     * Fixture unique link
     * @type {string}
     * @memberof FixtureUniqueLinkResponse
     */
    link: string;
}
