/* tslint:disable */
/* eslint-disable */
/**
 * GoMoney Basic Football-League Manager Service
 * This service provides endpoints for all `basic football-league manager` related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fatai@mail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Fixture } from './fixture';
/**
 * 
 * @export
 * @interface FixtureListResponse
 */
export interface FixtureListResponse {
    /**
     * 
     * @type {Array<Fixture>}
     * @memberof FixtureListResponse
     */
    records: Array<Fixture>;
}
