/* tslint:disable */
/* eslint-disable */
/**
 * GoMoney Football-League Manager Service
 * This service provides endpoints for all `football-league manager` related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fatai@mail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Team object
 * @export
 * @interface Team
 */
export interface Team {
    /**
     * Team unique identifier
     * @type {string}
     * @memberof Team
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    logoUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    updatedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof Team
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Team
     */
    updatedAt?: Date;
}
