/* tslint:disable */
/* eslint-disable */
/**
 * GoMoney Basic Football-League Manager Service
 * This service provides endpoints for all `basic football-league manager` related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fatai@mail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MatchResult } from './match-result';
/**
 * Update Fixture request data
 * @export
 * @interface UpdateFixtureDto
 */
export interface UpdateFixtureDto {
    /**
     * ID of Home Team
     * @type {string}
     * @memberof UpdateFixtureDto
     */
    homeTeamId?: string;
    /**
     * ID of Away Team
     * @type {string}
     * @memberof UpdateFixtureDto
     */
    awayTeamId?: string;
    /**
     * Date & Time that match starts
     * @type {Date}
     * @memberof UpdateFixtureDto
     */
    commencesAt?: Date;
    /**
     * 
     * @type {MatchResult}
     * @memberof UpdateFixtureDto
     */
    matchResult?: MatchResult;
}
