/* tslint:disable */
/* eslint-disable */
/**
 * GoMoney Football-League Manager Service
 * This service provides endpoints for all `football-league manager` related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fatai@mail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * User unique identifier
     * @type {string}
     * @memberof User
     */
    id: string;
    /**
     * User's email
     * @type {string}
     * @memberof User
     */
    email: string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isAdmin: boolean;
    /**
     * User's first-name
     * @type {string}
     * @memberof User
     */
    firstName?: string;
    /**
     * User's last-name
     * @type {string}
     * @memberof User
     */
    lastName?: string;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    createdAt: Date;
}
